# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pizzaria
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


  security:
    user:
      name: ${DEV_SECURITY_USER}
      password: ${DEV_SECURITY_PASSWORD}

server:
  port: ${DEV_SERVER_PORT}

app:
  url: http://localhost:${DEV_SERVER_PORT}