spring:
  config:
    activate:
      on-profile: homolog
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${HOMOLOGDB_URL}
    username: ${HOMOLOG_DB_USERNAME}
    password: ${HOMOLOG_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${HOMOLOG_SECURITY_USER}
      password: ${HOMOLOG_SECURITY_PASSWORD}

server:
  port: ${HOMOLOG_SERVER_PORT}

app:
  url: http://localhost:${DEV_SERVER_PORT}