spring:
  profiles:
    active: dev
    #active: homolog
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  jackson:
    time-zone: America/Sao_Paulo
    default-property-inclusion: non_null

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: "bG9yZW1pcHN1bS5kb2xvci4xMjM0NTY3ODkwISE="
    expiration: 86400000
jwt:
  refresh:
    expiration: 86400000

logging:
  level:
    root:
      org:
        springframework: DEBUG
