spring:
  profiles:
    active: dev
    #active: homolog
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  jackson:
    time-zone: America/Sao_Paulo
    default-property-inclusion: non_null

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
